### ISSUE TITLE
searching duck images and videos per command

### ISSUE THREAD

**Issue by Kryptuq** [ignorance-uwu/IgnoBot.py#5]
make bot react to i.duckimage and i.duckvideo to see random images/videos of a duck.

**Comment by milkyicedtea** [comment]
Finally done :uwuduck:

https://github.com/ignorance-uwu/IgnoBot.py/commit/05adc08a724fd78caf58f752f8ffe3414b576c4d#diff-95b0a8c0a5cae11500ee93d4ef43c0aebb3685b2113a9bca725ef2129c4a646
